apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-api
spec:
  selector:
    app: {{ .Release.Name }}-flask-api
  ports:
    - port: 5050
  type: {{ .Values.flaskApi.service.type }}
